name: install-chainweb-from-artifacts

inputs:
  os:
    description: the operating system of the build
    required: true
  ghc:
    description: GHC version of the build
    required: true

runs:
  using: 'composite'
  steps:
    # We can't use `uses: actions/download-artifact@v2` here to download artifacts
    - name: Install non-Haskell dependencies
      shell: bash
      run: |
        case "${{ inputs.os }}" in
        ubuntu*)
          sudo apt-get install -y z3 build-essential libsnappy-dev libgflags-dev
          wget https://github.com/facebook/rocksdb/archive/refs/tags/v6.29.3.tar.gz
          tar -xzvf v6.29.3.tar.gz
          cd rocksdb-6.29.3
          sudo make -j4 install-shared
          sudo ldconfig
          cd ..
          ;;
        mac*)
          brew update && brew install rocksdb z3 || true
          ;;
        *)
          echo "::error::unsupported operating system ${{ inputs.os }}"
          exit 1
          ;;
        esac
    - name: Install chainweb applications
      env:
        ARCHIVE_PATTERN: chainweb.${{ inputs.ghc }}.${{ inputs.os }}.*.tar.gz
      shell: bash
      run: |
          tar -xzf $ARCHIVE_PATTERN
          echo "`pwd`/chainweb" >> $GITHUB_PATH
    - name: test chainweb installation
      shell: bash
      run: chainweb-node --version
